
spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true   
      discovery: 
        enabled: true
        service-id: config-server
      name: item-service
      profile: dev 
      
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka